"""
OMNIX Driven Ports - Output Interfaces

These ports define contracts for external services that the application
depends on (databases, caches, exchanges, AI providers, etc.).

All driven ports are defined as typing.Protocol for structural subtyping,
allowing any class that implements the required methods to be used.
"""

from src.omnix.ports.driven.trading_port import TradingPort
from src.omnix.ports.driven.database_port import (
    DatabasePort,
    TradeRepositoryPort,
    PositionRepositoryPort,
    UserRepositoryPort,
)
from src.omnix.ports.driven.cache_port import CachePort
from src.omnix.ports.driven.ai_inference_port import AIInferencePort
from src.omnix.ports.driven.ai_text_gateway_port import (
    AITextGatewayPort,
    TextGenerationRequest,
    TextGenerationResponse,
    ModelInfo,
    ModelProvider,
)
from src.omnix.ports.driven.ai_voice_port import (
    AIVoicePort,
    TTSRequest,
    TTSResponse,
    STTRequest,
    STTResponse,
    VoiceLanguage,
    VoiceBiometricsResult,
)
from src.omnix.ports.driven.market_data_port import MarketDataPort, TechnicalIndicatorPort
from src.omnix.ports.driven.notification_port import NotificationPort
from src.omnix.ports.driven.market_intel_port import (
    MarketIntelPort,
    SentimentSnapshot,
    SentimentLevel,
    TechnicalIndicator,
    IndicatorType,
    NewsArticle,
    NewsCategory,
    MacroEvent,
    EarningsEvent,
    MarketIntelRequest,
    MarketIntelResponse,
)
from src.omnix.ports.driven.execution_port import (
    ExecutionPort,
    LiquidityReport,
    VolatilityMetrics,
    VolatilityRegime,
    CorrelationMatrix,
    ContagionLevel,
    SlippagePrediction,
    ExecutionTiming,
    ExecutionOrder,
    ExecutionResult,
    ExecutionStyle,
    ExecutionUrgency,
    MarketCondition,
)
from src.omnix.ports.driven.risk_control_port import (
    RiskControlPort,
    RiskAssessmentRequest,
    RiskDecision,
    RiskLevel,
    CircuitBreakEvent,
    CircuitBreakerState,
    LimitStatus,
    LimitType,
    PositionRisk,
    PortfolioRiskSummary,
    Alert,
    AlertPriority,
)
from src.omnix.ports.driven.derivatives_port import (
    DerivativesPort,
    FuturesContract,
    ContractType,
    DerivativesPosition,
    MarginStatus,
    MarginType,
    HedgeOrder,
    HedgeType,
    HedgeRecommendation,
    FundingAnalysis,
    DerivativesSummary,
)
from src.omnix.ports.driven.portfolio_port import (
    PortfolioPort,
    PortfolioPosition,
    PortfolioView,
    ExposureReport,
    RebalanceOrder,
    RebalanceCommand,
    RebalanceStrategy,
    TargetAllocation,
    AllocationPlan,
    AssetClass,
)
from src.omnix.ports.driven.optimization_port import (
    OptimizationPort,
    OptimizationConfig,
    OptimizationResult,
    OptimizationStatus,
    OptimizationObjective,
    WeightSet,
    WeightCategory,
    PerformanceForecast,
    ParameterSensitivity,
    LearningProgress,
)

__all__ = [
    "TradingPort",
    "DatabasePort",
    "TradeRepositoryPort",
    "PositionRepositoryPort",
    "UserRepositoryPort",
    "CachePort",
    "AIInferencePort",
    "AITextGatewayPort",
    "TextGenerationRequest",
    "TextGenerationResponse",
    "ModelInfo",
    "ModelProvider",
    "AIVoicePort",
    "TTSRequest",
    "TTSResponse",
    "STTRequest",
    "STTResponse",
    "VoiceLanguage",
    "VoiceBiometricsResult",
    "MarketDataPort",
    "TechnicalIndicatorPort",
    "NotificationPort",
    "MarketIntelPort",
    "SentimentSnapshot",
    "SentimentLevel",
    "TechnicalIndicator",
    "IndicatorType",
    "NewsArticle",
    "NewsCategory",
    "MacroEvent",
    "EarningsEvent",
    "MarketIntelRequest",
    "MarketIntelResponse",
    "ExecutionPort",
    "LiquidityReport",
    "VolatilityMetrics",
    "VolatilityRegime",
    "CorrelationMatrix",
    "ContagionLevel",
    "SlippagePrediction",
    "ExecutionTiming",
    "ExecutionOrder",
    "ExecutionResult",
    "ExecutionStyle",
    "ExecutionUrgency",
    "MarketCondition",
    "RiskControlPort",
    "RiskAssessmentRequest",
    "RiskDecision",
    "RiskLevel",
    "CircuitBreakEvent",
    "CircuitBreakerState",
    "LimitStatus",
    "LimitType",
    "PositionRisk",
    "PortfolioRiskSummary",
    "Alert",
    "AlertPriority",
    "DerivativesPort",
    "FuturesContract",
    "ContractType",
    "DerivativesPosition",
    "MarginStatus",
    "MarginType",
    "HedgeOrder",
    "HedgeType",
    "HedgeRecommendation",
    "FundingAnalysis",
    "DerivativesSummary",
    "PortfolioPort",
    "PortfolioPosition",
    "PortfolioView",
    "ExposureReport",
    "RebalanceOrder",
    "RebalanceCommand",
    "RebalanceStrategy",
    "TargetAllocation",
    "AllocationPlan",
    "AssetClass",
    "OptimizationPort",
    "OptimizationConfig",
    "OptimizationResult",
    "OptimizationStatus",
    "OptimizationObjective",
    "WeightSet",
    "WeightCategory",
    "PerformanceForecast",
    "ParameterSensitivity",
    "LearningProgress",
]
