"""
OMNIX V7.0 Risk Domain Entities
================================
Risk management entities for protection systems.

Models Risk Guardian, Circuit Breaker, and limit enforcement.
"""

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Optional, Dict, Any, List
from uuid import uuid4


class RiskLevel(Enum):
    """Risk severity levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"
    EMERGENCY = "emergency"
    
    @property
    def numeric_value(self) -> int:
        """Numeric value for comparison."""
        return {
            RiskLevel.LOW: 1,
            RiskLevel.MEDIUM: 2,
            RiskLevel.HIGH: 3,
            RiskLevel.CRITICAL: 4,
            RiskLevel.EMERGENCY: 5,
        }[self]
    
    def __lt__(self, other: "RiskLevel") -> bool:
        return self.numeric_value < other.numeric_value
    
    def __le__(self, other: "RiskLevel") -> bool:
        return self.numeric_value <= other.numeric_value
    
    def __gt__(self, other: "RiskLevel") -> bool:
        return self.numeric_value > other.numeric_value
    
    def __ge__(self, other: "RiskLevel") -> bool:
        return self.numeric_value >= other.numeric_value


class AlertType(Enum):
    """Types of risk alerts."""
    DRAWDOWN = "drawdown"
    DAILY_LOSS = "daily_loss"
    OVERTRADING = "overtrading"
    REVENGE_TRADE = "revenge_trade"
    POSITION_SIZE = "position_size"
    CORRELATION = "correlation"
    VOLATILITY = "volatility"
    LIQUIDITY = "liquidity"
    VETO = "veto"
    CIRCUIT_BREAKER = "circuit_breaker"
    EMERGENCY_STOP = "emergency_stop"


class CircuitBreakerStatus(Enum):
    """Circuit breaker states."""
    CLOSED = "closed"
    OPEN = "open"
    HALF_OPEN = "half_open"


@dataclass
class RiskAlert:
    """
    Risk alert generated by protection systems.
    
    Represents warnings and blocks from Risk Guardian,
    Coherence Engine vetoes, and circuit breakers.
    """
    id: str = field(default_factory=lambda: str(uuid4()))
    alert_type: AlertType = AlertType.DRAWDOWN
    level: RiskLevel = RiskLevel.MEDIUM
    message: str = ""
    
    created_at: datetime = field(default_factory=datetime.utcnow)
    expires_at: Optional[datetime] = None
    acknowledged_at: Optional[datetime] = None
    
    is_blocking: bool = False
    is_acknowledged: bool = False
    
    source: str = ""
    pair: Optional[str] = None
    user_id: Optional[str] = None
    
    current_value: Optional[float] = None
    threshold_value: Optional[float] = None
    
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    @classmethod
    def drawdown_alert(
        cls,
        current_drawdown: float,
        threshold: float,
        level: RiskLevel = RiskLevel.HIGH,
        blocking: bool = True,
    ) -> "RiskAlert":
        """Create drawdown alert."""
        return cls(
            alert_type=AlertType.DRAWDOWN,
            level=level,
            message=f"Drawdown {current_drawdown:.2%} exceeds threshold {threshold:.2%}",
            is_blocking=blocking,
            source="risk_guardian",
            current_value=current_drawdown,
            threshold_value=threshold,
        )
    
    @classmethod
    def daily_loss_alert(
        cls,
        current_loss: float,
        limit: float,
        level: RiskLevel = RiskLevel.CRITICAL,
    ) -> "RiskAlert":
        """Create daily loss limit alert."""
        return cls(
            alert_type=AlertType.DAILY_LOSS,
            level=level,
            message=f"Daily loss ${current_loss:.2f} reached limit ${limit:.2f}",
            is_blocking=True,
            source="risk_guardian",
            current_value=current_loss,
            threshold_value=limit,
            expires_at=datetime.utcnow().replace(hour=23, minute=59, second=59),
        )
    
    @classmethod
    def overtrading_alert(
        cls,
        trade_count: int,
        limit: int,
    ) -> "RiskAlert":
        """Create overtrading alert."""
        return cls(
            alert_type=AlertType.OVERTRADING,
            level=RiskLevel.MEDIUM,
            message=f"Trade count {trade_count} approaching limit {limit}",
            is_blocking=trade_count >= limit,
            source="risk_guardian",
            current_value=float(trade_count),
            threshold_value=float(limit),
        )
    
    @classmethod
    def veto_alert(
        cls,
        pair: str,
        reason: str,
        coherence_score: float,
    ) -> "RiskAlert":
        """Create Coherence Engine veto alert."""
        return cls(
            alert_type=AlertType.VETO,
            level=RiskLevel.HIGH,
            message=f"Signal vetoed for {pair}: {reason}",
            is_blocking=True,
            source="coherence_engine",
            pair=pair,
            current_value=coherence_score,
            metadata={"veto_reason": reason},
        )
    
    def acknowledge(self) -> None:
        """Acknowledge the alert."""
        self.is_acknowledged = True
        self.acknowledged_at = datetime.utcnow()
    
    def is_active(self) -> bool:
        """Check if alert is still active."""
        if self.expires_at and datetime.utcnow() > self.expires_at:
            return False
        return not self.is_acknowledged
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "id": self.id,
            "alert_type": self.alert_type.value,
            "level": self.level.value,
            "message": self.message,
            "is_blocking": self.is_blocking,
            "is_acknowledged": self.is_acknowledged,
            "source": self.source,
            "pair": self.pair,
            "current_value": self.current_value,
            "threshold_value": self.threshold_value,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "expires_at": self.expires_at.isoformat() if self.expires_at else None,
        }


@dataclass
class LimitState:
    """
    Current state of a trading limit.
    
    Tracks usage against configured limits for position sizes,
    trade counts, exposure, etc.
    """
    name: str = ""
    limit_type: str = ""
    
    current_value: float = 0.0
    max_value: float = 0.0
    warning_threshold: float = 0.8
    
    is_exceeded: bool = False
    is_warning: bool = False
    
    last_updated: datetime = field(default_factory=datetime.utcnow)
    reset_at: Optional[datetime] = None
    
    user_id: Optional[str] = None
    pair: Optional[str] = None
    
    @property
    def usage_ratio(self) -> float:
        """Calculate usage as ratio of limit."""
        if self.max_value == 0:
            return 0.0
        return self.current_value / self.max_value
    
    @property
    def remaining(self) -> float:
        """Calculate remaining capacity."""
        return max(0, self.max_value - self.current_value)
    
    def update(self, new_value: float) -> None:
        """Update current value and check thresholds."""
        self.current_value = new_value
        self.last_updated = datetime.utcnow()
        self.is_exceeded = new_value >= self.max_value
        self.is_warning = new_value >= (self.max_value * self.warning_threshold)
    
    def increment(self, amount: float = 1.0) -> bool:
        """Increment value if within limit. Returns True if successful."""
        if self.current_value + amount > self.max_value:
            return False
        self.update(self.current_value + amount)
        return True
    
    def reset(self) -> None:
        """Reset limit to zero."""
        self.current_value = 0.0
        self.is_exceeded = False
        self.is_warning = False
        self.last_updated = datetime.utcnow()
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "name": self.name,
            "limit_type": self.limit_type,
            "current_value": self.current_value,
            "max_value": self.max_value,
            "usage_ratio": self.usage_ratio,
            "remaining": self.remaining,
            "is_exceeded": self.is_exceeded,
            "is_warning": self.is_warning,
        }


@dataclass
class CircuitState:
    """
    Circuit breaker state for trading protection.
    
    Implements the circuit breaker pattern to prevent
    cascading failures during adverse conditions.
    """
    name: str = ""
    status: CircuitBreakerStatus = CircuitBreakerStatus.CLOSED
    
    failure_count: int = 0
    failure_threshold: int = 5
    success_count: int = 0
    success_threshold: int = 3
    
    last_failure_at: Optional[datetime] = None
    opened_at: Optional[datetime] = None
    half_open_at: Optional[datetime] = None
    
    cooldown_seconds: int = 300
    
    reason: str = ""
    
    @property
    def is_open(self) -> bool:
        """Check if circuit is open (blocking)."""
        return self.status == CircuitBreakerStatus.OPEN
    
    @property
    def is_closed(self) -> bool:
        """Check if circuit is closed (normal operation)."""
        return self.status == CircuitBreakerStatus.CLOSED
    
    @property
    def should_attempt_reset(self) -> bool:
        """Check if enough time has passed to attempt reset."""
        if self.status != CircuitBreakerStatus.OPEN:
            return False
        if not self.opened_at:
            return True
        elapsed = (datetime.utcnow() - self.opened_at).total_seconds()
        return elapsed >= self.cooldown_seconds
    
    def record_failure(self, reason: str = "") -> None:
        """Record a failure and potentially open circuit."""
        self.failure_count += 1
        self.last_failure_at = datetime.utcnow()
        self.reason = reason
        self.success_count = 0
        
        if self.failure_count >= self.failure_threshold:
            self._open()
    
    def record_success(self) -> None:
        """Record success and potentially close circuit."""
        self.success_count += 1
        
        if self.status == CircuitBreakerStatus.HALF_OPEN:
            if self.success_count >= self.success_threshold:
                self._close()
    
    def _open(self) -> None:
        """Open the circuit breaker."""
        self.status = CircuitBreakerStatus.OPEN
        self.opened_at = datetime.utcnow()
    
    def _close(self) -> None:
        """Close the circuit breaker."""
        self.status = CircuitBreakerStatus.CLOSED
        self.failure_count = 0
        self.success_count = 0
        self.opened_at = None
        self.half_open_at = None
        self.reason = ""
    
    def attempt_reset(self) -> bool:
        """Attempt to move from OPEN to HALF_OPEN."""
        if not self.should_attempt_reset:
            return False
        
        self.status = CircuitBreakerStatus.HALF_OPEN
        self.half_open_at = datetime.utcnow()
        self.success_count = 0
        return True
    
    def force_close(self) -> None:
        """Force close the circuit (manual override)."""
        self._close()
    
    def force_open(self, reason: str = "Manual override") -> None:
        """Force open the circuit (emergency stop)."""
        self.reason = reason
        self._open()
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "name": self.name,
            "status": self.status.value,
            "failure_count": self.failure_count,
            "failure_threshold": self.failure_threshold,
            "success_count": self.success_count,
            "reason": self.reason,
            "opened_at": self.opened_at.isoformat() if self.opened_at else None,
            "cooldown_seconds": self.cooldown_seconds,
        }
